apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
  - image: sabujjana/fortune
    name: fortunegenerator
    volumeMounts:
    - name: htmldump
      mountPath: /var/html
  - image: nginx:latest
    name: webserver
    volumeMounts:
    - name: htmldump
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: htmldump
    emptyDir: {}

